[[redirects]]
  from = "http://*"
  to = "https://://splat"
  status = 301
  force = true
  [[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'"